
["Basic Ender Gate"]
	#Range: min = 0, max = 2147483647
	transfer = "4000"
	#Range: min = 1, max = 16
	channels = "2"

["Hardened Ender Gate"]
	#Range: min = 0, max = 2147483647
	transfer = "8000"
	#Range: min = 1, max = 16
	channels = "4"

["Blazing Ender Gate"]
	#Range: min = 0, max = 2147483647
	transfer = "16000"
	#Range: min = 1, max = 16
	channels = "7"

["Niotic Ender Gate"]
	#Range: min = 0, max = 2147483647
	transfer = "32000"
	#Range: min = 1, max = 16
	channels = "11"

["Spirited Ender Gate"]
	#Range: min = 0, max = 2147483647
	transfer = "64000"
	#Range: min = 1, max = 16
	channels = "16"

