
#Range: min = 0, max = 2147483647
["Basic Energy Cable"]
	transfer = "100"

["Hardened Energy Cable"]
	transfer = "2000"

["Blazing Energy Cable"]
	transfer = "4000"

["Niotic Energy Cable"]
	transfer = "8000"

["Spirited Energy Cable"]
	transfer = "16000"

