
#General options
[general]
	#Display the status and the current FPS at the specified location.
	#(0:off, 1:top-left, 2:top-right, 3:bottom-right, 4:bottom-left)
	#Range: 0 ~ 4
	hudLocation = 0
	#Detect movement of player position. (0:OFF, 1:Riding/Flying, 2:Always)
	#Range: 0 ~ 2
	detectMoving = 1
	#Ignore the mouse button holding.
	ignoreHoldButton = false
	#Frame rate during reducing.
	#Range: 1 ~ 60
	idleFps = 10
	#Suppress master volume if the window is inactive.
	suppressSound = false
	#Behavior of HUD display when a chat window opened. (0:keep to display, 1:off, 2:dodge a chat box)
	#Range: 0 ~ 2
	hudBehindChatBox = 2
	#Frame rate during GUI screen(Inventory/Menu) is opened.(0:OFF)
	#Range: 0 ~ 60
	guiScreenFps = 0
	#Enable reducing FPS when no user activity has been sensed for a certain time.
	enableFpsReducer = true
	#Waiting time(sec) until reducing FPS.
	#Range: 0 ~ 86400
	waitingTime = 300
	#HUD scale (default: 1.0)
	#Range: 0.1 ~ 2.0
	hudScale = 1.0
	#Force reducing FPS if the window is inactive.
	reducingInBackground = true
	#Suppression master volume ratio in inactive (0-100).
	#Range: 0 ~ 100
	suppressedVolume = 100

#Extra options
[extra]
	#HUD color
	hudColor = "f0f0f0"
	#Pre-text of FPS display in GUI screen(inventory and menu).
	hudGuiModePreText = "FPS: "
	#HUD color for FPS display in GUI screen(inventory and menu).
	hudGuiModeColor = "00f0f0"
	#Pre-text of reduced FPS display.
	hudReductionPreText = "ECO MODE: "
	#Y margin of HUD position from the corner of the screen.
	#Range: > -2147483648
	hudMarginY = 2
	#Allow player configuration mode.
	allowPlayerConfig = true
	#X margin of HUD position from the corner of the screen.
	#Range: > -2147483648
	hudMarginX = 2
	#Pre-text of FPS display.
	hudPreText = "FPS: "
	#Reduced fps HUD color
	hudReductionColor = "00ff00"

#Debug options
[debug]
	#Show event log on the game screen.
	logInChat = false
	#Enable debug log
	debugLog = false

