
#Bamboo Blocks Settings
[bambooblocks]
	#Set length of Bamboo Button pulse in seconds
	#Range: > 0
	ticks = 2
	#Set fuel burn time of Bamboo Torches
	#Range: > -1
	burn_time = 50
	#Toggle Reed Thatch
	reed_thatch = true
	#Set Sensitivity of Bamboo Pressure Plates
	#Allowed Values: ALL, MOBS, PLAYER
	sensitivity = "ALL"
	#Toggle Bamboo Torches
	bamboo_torches = true
	#Toggle Bamboo Torches
	bamboo_planks = true

