
[core]

	[core.general]
		#If an anonymous mod startup analytics request may be sent to our analytics service.
		analytics = true
		#If the version checker should be enabled.
		versionChecker = true
		#If the recipe loader should crash when finding invalid recipes.
		crashOnInvalidRecipe = false
		#If mod compatibility loader should crash hard if errors occur in that process.
		crashOnModCompatCrash = false

[block]

	[block.ranged_capability_proxy]
		#The maximum range in number of blocks. Warning: high values can lag and/or crash your game.
		range = 16

