
[Tooltips]
	#If TRUE, Item descriptions will be added to their tooltips if possible.
	"Show Item Descriptions" = true
	#If TRUE, Enchantment descriptions will be added to the tooltip for Enchanted Books containing only a single enchantment.
	"Show Enchantment Descriptions" = false

