
#Crafting Tweaks Client Configuration
[client]
	#Set this to true if you don't want the tweak buttons' tooltips to show.
	hideButtonTooltips = false
	#This option is toggled by the 'Toggle Buttons' key that can be defined in the Controls settings.
	hideButtons = false
	#We both know JEI is much better. This option hides Vanilla's crafting book button instead of moving it.
	hideVanillaCraftingGuide = false
	#If set to true, right-clicking the result slot in a crafting table will craft a full stack.
	rightClickCraftsStack = true

	[client.addons]
		#State of this addon. Can be ENABLED, BUTTONS_ONLY, HOTKEYS_ONLY or DISABLED.
		minecraft = "ENABLED"
		#State of this addon. Can be ENABLED, BUTTONS_ONLY, HOTKEYS_ONLY or DISABLED.
		refinedstorage = "ENABLED"
		#State of this addon. Can be ENABLED, BUTTONS_ONLY, HOTKEYS_ONLY or DISABLED.
		craftingstation = "ENABLED"
		#State of this addon. Can be ENABLED, BUTTONS_ONLY, HOTKEYS_ONLY or DISABLED.
		fastbench = "ENABLED"

