
[oregeneration]
	#Determines the rarity of amber veins.
	#Range: 1 ~ 200
	amber_weight = 2
	#Determines the rarity of rockroot veins.
	#Range: 1 ~ 200
	rockroot_weight = 16
	#Determines the rarity of fiery glass veins.
	#Range: 1 ~ 200
	fiery_glass_weight = 5
	#Determines the size of an amber vein.
	#Range: 1 ~ 32
	amber_size = 4
	#Determines the size of a moonstone vein.
	#Range: 1 ~ 32
	moonstone_size = 4
	#Determines the rarity of moonstone veins.
	#Range: 1 ~ 200
	moonstone_weight = 3
	#Determines the size of a fiery glass vein.
	#Range: 1 ~ 32
	fiery_glass_size = 7
	#Whether to have ores from this mod spawn at all.
	generate_ores = true
	#Determines the size of a rockroot vein.
	#Range: 1 ~ 32
	rockroot_size = 3

[toolcontrollers]
	#Decides what blocks are allowed and not allowed to be affected by the sickle.
	#Adding '+' to the start of the block will add it, and '-' will remove it.
	sickle_block_list = []

[droprate]
	#Rate of hemp seed drops from grass blocks.
	#Range: 0 ~ 100
	hemp_seed_rate = 8
	#Whether to have seeds from this mod drop from grass at all.
	drop_seeds = true

