
[controls]
	#If true, stat icon visibility is changed by holding shift.
	#Otherwise, they are always visible.
	checkShiftKey = true
	#Only applies if checkShiftKey is enabled.
	#If this is true, stat icons are hidden when shift is held.
	#Otherwise, stat icons are shown only when shift is held.
	hideOnShift = false

[display]
	#Fine-tune the position of the icons line
	offsetX = 0
	#Background color, including alpha (AARRGGBB)
	backgroundColor = "#C0100010"
	#Fine-tune the position of the icons line
	offsetY = 0
	#Scale of stat values
	fontScale = 1.0
	#Move the stat icons below the tooltip window, instead of on top of it
	positionOnBottom = false

