#Should the Wrench show up in the creative menu?
creative_wrench = true
#How should very large and small numbers be displayed?
#Options are: NORMAL, SCIENTIFIC, ENGINEERING, and RAW
#Allowed Values: NORMAL, SCIENTIFIC, ENGINEERING, RAW
num_display = "SCIENTIFIC"

