
[General]
	#The chance after the quartz roll that the next spreaded block is netherbrick.
	#Range: 0.0 ~ 1.0
	isNetherBrickChance = 0.25
	#The chance the next spreaded block is quartz ore.
	#Range: 0.0 ~ 1.0
	isQuartzChance = 0.1
	#The amount of blocks that are instantly converted to a nether block around a portal when it is detected. If there are existing nether blocks within the radius, their count is substracted from this number.
	#Range: 0 ~ 1000
	instantConvertAmount = 5
	#The radius around the portal to which the nether blocks can spread.
	#Range: 1 ~ 100
	portalSpreadRadius = 4
	#The delay in ms in between the spread around the nether portal.
	#Range: 20 ~ 360000
	spreadDelay = 2500
	#When enabled, blocks the spread effect when there are two coal blocks within the radius.
	coalPreventsSpread = true

