
[general]
	#Set this to true to disable advancement locking and make all entries visible at all times\nConfig Flag: advancements_disabled
	"Disable Advancement Locking" = false
	#Set this to the ID of a book to have it show up in players' inventories, replacing the recipe book.
	"Inventory Button Book" = ""
	#Enable testing mode. By default this doesn't do anything, but you can use the config flag in your books if you want.\nConfig Flag: testing_mode
	"Testing Mode" = false

