
#Settings for the teleportation system
[teleporter]
	#The vertical range the dialing device uses to check for transmitters
	#Range: > 0
	verticalDialerRange = 5
	#This is the amount of RF that is consumed at a boosted transmitter in case the receiver doesn't have enough power
	#Range: > 0
	rfBoostedTeleport = 20000
	#The volume for the error sound when teleportation fails (1.0 is default)
	#Range: 0.0 ~ 1.0
	volumeTeleportError = 1.0
	#The amount of time that is added depending on distance for a local teleport. This value is in militicks which means that 1000 is one tick and one tick is 1/20 of a second
	#Range: > 0
	timeTeleportDist = 10
	#Comma separated list of dimension ids that the teleportation system can't teleport from
	blacklistedTeleportationSources = ""
	#For every unit in distance this value is added to the initial RF cost for starting the teleportation. This value is not used when teleporting to another dimension
	#Range: > 0
	rfStartTeleportDist = 10
	#Maximum RF storage that the dialing device can hold
	#Range: > 0
	dialerMaxRF = 50000
	#Set this to false to disable the 'whoosh' message on teleport
	whooshMessage = true
	#The amount of RF that is consumed by the matter transmitter when a dial is active
	#Range: > 0
	rfDialedConnectionPerTick = 10
	#The speed bonus for the advanced charged porter (compared to the normal one)
	#Range: > 0
	advancedSpeedBonus = 4
	#Maximum RF storage that the matter receiver can hold
	#Range: > 0
	receiverMaxRF = 100000
	#For the duration of the teleport process this value represents the amount of RF that is consumed by the matter transmitter for every tick
	#Range: > 0
	rfTeleportPerTick = 500
	#This is the amount of RF that is consumed at the receiving side for every teleport. This RF is only consumed when the teleportation actually happens
	#Range: > 0
	rfPerTeleportReceiver = 5000
	#If this is true then the RFTools teleportation system cannot be used to travel in the same dimension
	preventInterdimensionalTeleports = false
	#RF per tick that the matter transmitter can receive. It is recommended to keep this at least equal to 'rfTeleportPerTick'
	#Range: > 0
	transmitterRFPerTick = 1000
	#The base time used for a teleportation for a local teleport. The 'timeTeleportDist' value is added per distance traveled
	#Range: > 0
	timeTeleportBaseLocal = 5
	#RF per tick that the dialing device can receive
	#Range: > 0
	dialerRFPerTick = 100
	#Maximum RF storage that the matter transmitter can hold. This should be at least equal to 'rfStartTeleportDim'
	#Range: > 0
	transmitterMaxRF = 200000
	#RF per tick that the matter receiver can receive
	#Range: > 0
	receiverRFPerTick = 500
	#The amount of ticks that a matter transmitter with destination checker will wait before checking a receiver in case the world is not loaded (-1 to disable this check completely)
	#Range: > -1
	checkUnloadedWorld = -1
	#If this is true then all usages of the teleport system are logged
	logTeleportUsages = false
	#Maximum RF storage that the advanced charged porter item can hold (note that teleporting this way uses 50% more RF then with a matter transmitter)
	#Range: > 0
	advancedChargedPorterMaxRF = 1000000
	#Maximum RF storage that the charged porter item can hold (note that teleporting this way uses 50% more RF then with a matter transmitter)
	#Range: > 0
	chargedPorterMaxRF = 200000
	#The amount of ticks that a matter transmitter with destination checker will wait before checking a receiver in case the chunk is not loaded (-1 to disable this check completely)
	#Range: > -1
	checkUnloadedChunk = -1
	#The amount of RF consumed when the dialing device checks for the capabilities of a receiver ('Check' button)
	#Range: > 0
	rfPerCheck = 5000
	#The volume for the teleporting sound (1.0 is default)
	#Range: 0.0 ~ 1.0
	volumeTeleport = 1.0
	#Comma separated list of dimension ids that the teleportation system can't teleport to
	blacklistedTeleportationDestinations = ""
	#The base time used for a teleportation to another dimension. The 'timeTeleportDist' value is not used
	#Range: > 0
	timeTeleportBaseDim = 50
	#The horizontal range the dialing device uses to check for transmitters. These are the transmitters the dialing device will be able to control
	#Range: > 0
	horizontalDialerRange = 10
	#RF per tick that the the charged porter item can receive
	#Range: > 0
	chargedPorterRFPerTick = 2000
	#The amount of RF/tick an idle dialed transmitter consumes
	#Range: > 0
	rfMatterIdleTick = 0
	#The amount of RF that is consumed by a matter transmitter when the player goes to stand in the teleportation beam allowing the teleportation process to start. This value is used for a teleport in the same dimension. In addition to this value the 'rfStartTeleportDist' is also added per traveled distance
	#Range: > 0
	rfStartTeleportLocal = 5000
	#The amount of RF that is consumed by a matter transmitter when the player goes to stand in the teleportation beam allowing the teleportation process to start. This version is for a teleportation to another dimension and in this case 'rfStartTeleportDist' is not used. This value also acts as the maximum rf that can be consumed for a local teleport
	#Range: > 0
	rfStartTeleportDim = 100000
	#The amount of RF consumed when dialing a transmitter to another receiver
	#Range: > 0
	rfPerDial = 1000

#Settings for the crafter
[crafter]
	#Maximum RF storage that the crafter can hold
	#Range: > 0
	crafterMaxRF = 50000
	#RF per tick that the crafter can receive
	#Range: > 0
	crafterRFPerTick = 500
	#Amount of RF used per crafting operation
	#Range: > 0
	rfPerOperation = 100
	#How many operations to do at once in fast mode
	#Range: > 0
	speedOperations = 5
	#Whether the crafter should exist
	enabled = true

#Settings for the tank
[tank]
	#Maximum tank capacity (in mb)
	#Range: > 0
	maxCapacity = 32000

