
#Dimensional shard ore generation
[worldgen]

	#Overworld
	[worldgen.nether]
		#Number of times to try generate the ore (set to 0 to disable)
		#Range: 0 ~ 256
		oreChances = 8
		#Max height
		#Range: 0 ~ 256
		oreMax = 40
		#Max size of veins
		#Range: 1 ~ 256
		oreVeinsize = 8
		#Min height
		#Range: 0 ~ 256
		oreMin = 2

	#Overworld
	[worldgen.overworld]
		#Number of times to try generate the ore (set to 0 to disable)
		#Range: 0 ~ 256
		oreChances = 1
		#Max height
		#Range: 0 ~ 256
		oreMax = 40
		#Max size of veins
		#Range: 1 ~ 256
		oreVeinsize = 3
		#Min height
		#Range: 0 ~ 256
		oreMin = 2

#Settings for the infusing system
[infuser]
	#Maximum RF storage that the infuser can hold
	#Range: > 0
	infuserMaxRF = 100000
	#RF per tick that the infuser can receive
	#Range: > 0
	infuserRFPerTick = 10000
	#Maximum amount of dimensional shards before a machine is fully infused
	#Range: > 1
	maxInfuse = 256
	#Amount of RF used per tick while infusing
	#Range: > 0
	usePerTick = 1000

