
#Client config options
[client]
	#How long one move wheel movement for scrolling lists
	#Range: 1 ~ 256
	ScrollSpeed = 20
	#Default value for InspectionBoxHighlighting (modifiable in-game via command /sfm settings, but does not persist)
	EnableInspections = false
	#Enable to use vanilla background instead of a plain rectangle
	UseBackgroundOnFullscreen = false
	#Determines how fast arrow keys moving is (for editor panel)
	#Range: > 0
	DefaultEditorMoveSpeed = 2
	#Determines how fast arrow keys moving is, while Shift is pressed
	#Range: > 0
	AcceleratedEditorMoveSpeed = 20

