
#Factory manager config options
[factoryManager]
	#Maximum depth that the Factory Manager DFS algorithm should go
	#Range: > 0
	MaxSearchDepth = 64
	#Number of ticks for the Factory Manager to rescan the network. Set to -1 to make it never rescan passively
	#Range: > -1
	RescanInterval = 100

#Procedures config options
#Run '/sfm reload componentGroups' after updating config
[procedures]
	EnableItemImport = true
	EnableRedstoneTrigger = true
	EnableItemExport = true
	EnableRedstoneEmitter = true
	EnableIntervalTrigger = true
	EnableItemTransfer = true
	EnableCrafting = true

#Block property config options
[blocks]
	#Whether the redstone emitter block is considered a cable
	IsRedstoneEmitterBlockCables = false
	#Whether the redstone input block is considered a cable
	IsRedstoneInputBlockCables = false

