
#General settings
[storagenetwork]
	#Enable very spammy logs.  Sometimes useful for debugging. 
	logSpam = false
	#If this is true, reload network when a chunk unloads, this keeps your network always up to date.  It has been reported that this cause lag and chunk load issues on servers, so disable if you have any problems. 
	reloadNetworkWhenUnloadChunk = false
	#How often to auto-refresh a network (one second is 20 ticks)
	#Range: 2 ~ 4096
	autoRefreshTicks = 20
	#Disable these blocks from ever being able to connect to the network, they will be treated as a non-inventory.
	BlacklistBlocks = ["extrautils2:playerchest"]

