
#Personal Options that can be edited even on server
[client]
	#Decimal value for the color of the grave text <Death Date> [0..16777215|default:2962496]
	#Range: 0 ~ 16777215
	text_color_death_date = 2962496
	#Shows all the infos in the tooltip of items [false/true|default:true]
	show_enhanced_tooltips = true
	#Shows shadow step particles [false/true|default:true]
	hide_shadow_step = true
	#Shows the magic circles when using some items [false/true|default:true]
	show_magic_circle = true
	#Equips elytra in priority when recovering your lost items [false/true|default:false]
	equip_elytra_in_priority = false
	#Shows the use of the Tombstone's enchantments in tooltip [false/true|default:true]
	show_info_on_enchantment = true
	#Decimal value for the color of the grave text <Owner Name> [0..16777215|default:5991302]
	#Range: 0 ~ 16777215
	text_color_owner = 5991302
	#Decimal value for the color of the particles when using magic items [0..16777215|default:125656]
	#Range: 0 ~ 16777215
	particle_casting_color = 125656
	#Favorite grave marble
	#Allowed Values: DARK, WHITE
	favorite_grave_marble = "DARK"
	#Highlights the tomb from far when holding the key [false/true|default:true]
	highlight = true
	#Enables the special rendering and particles for Halloween [false/true|default:true]
	enable_halloween_effect = true
	#Favorite grave
	#Allowed Values: GRAVE_SIMPLE, GRAVE_NORMAL, GRAVE_CROSS, TOMBSTONE, SUBARAKI_GRAVE
	favorite_grave = "GRAVE_SIMPLE"
	#Defines the rule to use for grave's skin [DEFAULT/FORCE_NORMAL/FORCE_HALLOWEEN|default:DEFAULT]
	#Allowed Values: DEFAULT, FORCE_NORMAL, FORCE_HALLOWEEN
	grave_skin_rule = "DEFAULT"
	#Fog density around the graves [NONE/LOW/NORMAL/HIGH|default:LOW]
	#Allowed Values: NONE, LOW, NORMAL, HIGH
	fog_density = "LOW"
	#Skips the Respawn Screen [false/true|default:false]
	skip_respawn_screen = false
	#Decimal value for the color of the grave text <R.I.P.> [0..16777215|default:2962496]
	#Range: 0 ~ 16777215
	text_color_rip = 2962496
	#Display or not the messages of gain of points in knowledge of death [false/true|default:true]
	display_knowledge_message = true
	#Shows only the elapsed minecraft days since the death on graves [false/true|default:false]
	date_in_mc_time = false

