
#Miscellaneous options
[general]
	#Whether to log the positions of players' graves [false/true|default:true]
	log_player_grave = true
	#Prevents death outside of world borders [false/true|default:false]
	prevent_death_outside_world = false
	#Allows player's graves to appear in water [false/true|default:true]
	allow_grave_in_water = true
	#The chance that creatures appear after the contents of a grave are retrieved [0..100|default:0]
	#Range: 0 ~ 100
	chance_mob_on_grave_recovery = 0
	#Whether to restore beneficial effects after a player dies [false/true|default:true]
	restore_effects_on_death = true
	#The chance that some items are lost on death [0..100|default:0]
	#Range: 0 ~ 100
	chance_loss_on_death = 0
	#The Halloween features also happen outside the dates of the event [false/true|default:false]
	persistant_halloween = false
	#The radius in which items should be collected when a grave is spawned [1..10|default:5]
	#Range: 1 ~ 10
	sniffer_range = 5
	#Whether to require a Grave's Key to access graves [false/true|default:true]
	player_grave_access = true
	#Whether to cancel the Ghostly Shape effect on breaking a block or opening a chest [false/true|default:false]
	nerf_ghostly_shape = false
	#Graveless Areas
	no_grave_location = ["0, 0, 0, -10000, 20"]
	#Increases the minimum time without sleeping for phantom spawn around player based on their level in Knowledge of Death [false/true|default:true]
	knowledge_reduce_phantom_spawn = false
	#Knowledge of Death loss why dying [0..500|default:0]
	#Range: 0 ~ 500
	knowledge_loss = 0
	#Minimum time without sleeping for phantom to spawn around players [1200..MAX|default:72000]
	#Range: > 1200
	time_for_phantom_spawn = 72000
	#Allows players to be hurt by special damages related to some items [false/true|default:true]
	allow_beyond_the_grave_damage = true
	#Allows teleportation to other dimensions [false/true|default:true]
	teleport_dim = true
	#Effects that are never preserved on death
	black_list_effects = ["tombstone:ghostly_shape", "tombstone:preservation", "tombstone:exorcism", "minecraft:bad_omen", "minecraft:glowing"]
	#The percentage of items that are lost on death [0..100|default:0]
	#Range: 0 ~ 100
	percent_loss_on_death = 0
	#Whether graves should be allowed to bypass anti-griefing rules [false/true|default:true]
	graves_bypass_griefing_rules = true
	#Enables PvP mode, which allows players to open graves of players they kill [false/true|default:false]
	pvp_mode = false
	#Whether to handle player death [false/true|default:true]
	handle_player_death = true
	#Whether to always give players a Grave's Key on death [false/true|default:true]
	grave_key_on_death = true

#Allows to define the conditions for a village siege to begin
[village_siege]
	#Undeads always wear a helm when sieging [false/true|default:false]
	undead_wear_helm_in_siege = false
	#Shuffles the list of players before testing the siege location [false/true|default:true]
	shuffle_players_for_siege = true
	#Logs the different states of a village siege while searching for an adequate place [false/true|default:false]
	log_siege_state = false
	#Allows to use the positions of creative players to define the siege location [false/true|default:true]
	allow_creative_players_for_siege = true
	#Delay in seconds for a second test of siege when the first failed [0..2400|default:600]
	#Range: 0 ~ 2400
	delay_siege_test = 600
	#The creatures of the siege have a glowing effect (only uses this for test purposes) [false/true|default:false]
	glowing_creature_test = false
	#Allows to handle village sieges [false/true|default:true]
	handle_village_siege = false
	#Maximum of creatures appearing in a siege [0..100|default:20]
	#Range: 0 ~ 100
	siege_max_creature = 20
	#Chance for a siege to occur [0..100|default:10]
	#Range: 0 ~ 100
	siege_chance = 0
	#Mobs in siege are persistent [false/true|default:false]
	persistent_mob_in_siege = false

#For settings related to decorative tombs and magic items
[decorative_grave]
	#The creatures that can't be captured in receptacle
	black_list_capturable_souls = []
	#The cooldown in minutes to reset the perks with the Ã‚nkh of Pray [0..60|default:20]
	#Range: 0 ~ 60
	cooldown_reset_perk = 20
	#Allows the purification effect to clear neutral effects [false/true|default:true]
	purification_affect_neutral_effects = true
	#Chance to receive a random beneficial spell effect when praying near a grave [0..100|default:40]
	#Range: 0 ~ 100
	chance_pray_reward = 40
	#Allows lost tablets to find locations outside the current world [false/true|default:true]
	allow_tablet_search_outside_world = true
	#Chance on 1000 that a soul appears on a grave [0..1000|default:100]
	#Range: 0 ~ 1000
	chance_soul = 0
	#Time in minutes to check if a soul appears on a grave [10..10000|default:30]
	#Range: 10 ~ 10000
	time_soul = 30

#Allows to customize or disable the enchantments
[enchantments]
	#Restricts the effect of Shadow Step to players [false/true|default:true]
	restrict_shadow_step_to_player = true

#Options related to the command recovery and auto-save of players
[recovery]
	#Enables to backup automatically players [false/true|default:true]
	recovery_player_enable = true
	#Enables to backup automatically dead familiars [false/true|default:true]
	recovery_familiar_enable = true
	#Time in minutes between players' backups [10..1000|default:40]
	#Range: 10 ~ 1000
	recovery_player_timer = 30
	#Maximum number of backups per player [5..100|default:15]
	#Range: 5 ~ 100
	recovery_player_max_saves = 15

#Allows to change the chance to drop some items
[loot]
	#Allows the undeads to have a low chance to drop their skull [false/true|default:true]
	undead_can_drop_skull = true
	#Chance on 1000 to receive a random scroll on undead boss [0..1000|default:100]
	#Range: 0 ~ 1000
	chance_random_scroll_on_boss = 0
	#Chance on 1000 to receive a random poppet on undead boss [0..1000|default:100]
	#Range: 0 ~ 1000
	chance_random_poppet_on_boss = 0
	#Chance on 1000 for undead mobs to drop Grave's Dust [0..1000|default:100]
	#Range: 0 ~ 1000
	chance_grave_dust = 0
	#Chance on 1000 to receive a decorative grave on undead boss [0..1000|default:50]
	#Range: 0 ~ 1000
	chance_decorative_grave_on_boss = 0
	#Chance on 1000 to receive a Soul Receptacle on undead boss [0..1000|default:50]
	#Range: 0 ~ 1000
	chance_soul_receptacle_on_boss = 0
	#Defines the allowed loottables having a chance to contain a magic item from Tombstone
	treasure_loot_table = []

#Allows to enable some features related to others mods
[compatibility]
	#Keeps the cosmetic armor when you die [false/true|default:true]
	keep_cosmetic_armor = false
	#Allows to auto-equip the slots from Curio mod [false/true|default:true]
	allow_curio_auto_equip = true

